export const TITLE = 'title'
export const CONTENT = 'content'
export const MATERIAL = 'material'
export const IDDISCUSSION = 'idDiscussion'

export const FORM_TITLE = 'title'
export const FORM_DATE = 'date'
export const FORM_DESCRIPTION = 'description'
export const FORM_SHORTANSWER = 'shortAnswer'
export const FORM_SELECT = 'select'
export const FORM_SELECTQUSITION = 'selectQusition'
export const FORM_SELECTANSWER = 'selectAnswer'
export const FORM_SELECTOPTION = 'selectOption'
export const FORM_TRUEFALSE = 'TrueFalseAnswer'
export const FORM_STATUS = 'status'
export const FORM_AUTHOR = 'author'
